# Generated by Django 4.1.7 on 2023-03-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='HanJi',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('han_ji', models.CharField(default='', max_length=2)),
                ('chu_im', models.CharField(default='', max_length=10)),
                ('freq', models.FloatField(null=True)),
                ('siann', models.CharField(default='', max_length=2)),
                ('un', models.CharField(default='', max_length=5)),
                ('tiau', models.IntegerField(null=True)),
                ('old_chu_im', models.CharField(max_length=10, null=True)),
                ('sni_siann', models.CharField(default='', max_length=10)),
                ('sni_un', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
