sip_ngoo_im_un_bu = {
    '君': ['un', 'ut'],
    '堅': ['ian', 'iat'],
    '金': ['im', 'ip'],
    '規': ['ui', 'uih'],
    '嘉': ['ee', 'eeh'],
    '干': ['an', 'at'],
    '公': ['ong', 'ok'],
    '乖': ['uai', 'uaih'],
    '經': ['ing', 'ik'],
    '觀': ['uan', 'uat'],
    '沽': ['oo', 'ooh'],
    '嬌': ['iau', 'iauh'],
    '稽': ['ei', 'eih'],
    '恭': ['iong', 'iok'],
    '高': ['o', 'oh'],
    '皆': ['ai', 'aih'],
    '巾': ['in', 'it'],
    '姜': ['iang', 'iak'],
    '甘': ['am', 'ap'],
    '瓜': ['ua', 'uah'],
    '江': ['ang', 'ak'],
    '兼': ['iam', 'iap'],
    '交': ['au', 'auh'],
    '迦': ['ia', 'iah'],
    '檜': ['ue', 'ueh'],
    '監': ['ann', 'ahnn'],
    '艍': ['u', 'uh'],
    '膠': ['a', 'ah'],
    '居': ['i', 'ih'],
    '丩': ['iu', 'iuh'],
    '更': ['enn', 'ehnn'],
    '褌': ['uinn', 'uinnh'],
    '茄': ['io', 'ioh'],
    '梔': ['inn', 'ihnn'],
    '薑': ['ionn', 'ionnh'],
    '驚': ['iann', 'iannh'],
    '官': ['uann', 'uannh'],
    '鋼': ['ng', 'ngh'],
    '伽': ['e', 'eh'],
    '閒': ['ainn', 'ainnh'],
    '姑': ['onn', 'onnh'],
    '姆': ['m', 'mh'],
    '光': ['uang', 'uak'],
    '閂': ['uainn', 'uaihnn'],
    '糜': ['uenn', 'uennh'],
    '嘄': ['iaunn', 'iauhnn'],
    '箴': ['om', 'op'],
    '爻': ['aunn', 'aunnh'],
    '扛': ['onn', 'ohnn'],
    '牛': ['iunn', 'iunnh'],
}

new_sip_ngoo_im_un_bu = {}
for key, values in sip_ngoo_im_un_bu.items():
    for value in values:
        new_sip_ngoo_im_un_bu[value] = key

print(new_sip_ngoo_im_un_bu)
